# Generated by Django 3.0.6 on 2020-05-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200508_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=64)),
                ('totalPrice', models.FloatField()),
                ('pizzas', models.ManyToManyField(blank=True, related_name='in_order', to='orders.Pizza')),
            ],
        ),
    ]
